name: e2e-reused

on:
  #schedule:
  #  - cron: '0 0/24 * * *' #Execute every 6 hours
  workflow_dispatch 

jobs: 

  data-ingestion:
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-ingestion.yml@main
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  
  data-forecast:
    needs: data-ingestion
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-forecast.yml@main
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

  data-monitoring:
    needs : [data-ingestion, data-forecast]
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-monitoring.yml@main
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

