name: e2e

on:
  #schedule: 
  #  - cron: '0 0/24 * * *' #Execute every 6 hours
  workflow_dispatch 

jobs:

  data-ingestion:
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-ingestion.yml@main
  
  data-forecast:
    needs: data-ingestion
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-forecast.yml@main

  data-monitoring:
    needs : [data-ingestion, data-forecast]
    uses: krishnajiraoh/my-crypto-world/.github/workflows/data-monitoring.yml@main

