name: forecast

on:
  schedule:
   - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r forecast/requirements.txt
          
      - name: Forecast and send out notifications
        env: 
          COINS: bitcoin,ethereum,solana
          LOOK_BACK_DAYS: 30 
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: "Crypto Forecasts"
        run: |
          cd forecast 
          python Forecast.py --no-pylint run
