name: test_ta-lib

on:
  #schedule:
  #  - cron: '0 0/24 * * *' #Execute every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Install ta-lib cython lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar xvfz ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure
          make
          sudo make install 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install TA-Lib
          
      - name: Test TA-Lib
        run: |
          import talib
          import numpy
          c = numpy.random.randn(40)
          print(talib.SMA(c))
